name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Nix
        uses: cachix/install-nix-action@v12
      - name: Build
        run: 'nix-build -I nixpkgs=channel:nixos-20.09 --quiet release.nix -A nixops-packet.x86_64-linux --show-trace'
        env:
          NIX_PATH: "nixpkgs=channel:nixos-20.09"
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Nix
        uses: cachix/install-nix-action@v12
      - name: Black
        run: 'nix-shell ./shell.nix --run "black --check ."'
        env:
          NIX_PATH: "nixpkgs=channel:nixos-20.09"
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Nix
        uses: cachix/install-nix-action@v12
      - name: Flake8
        run: 'nix-shell ./shell.nix --run "flake8 nixops_packet"'
        env:
          NIX_PATH: "nixpkgs=channel:nixos-20.09"
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Nix
        uses: cachix/install-nix-action@v12
      - name: Mypy
        run: 'nix-shell ./shell.nix --run "mypy nixops_packet"'
        env:
          NIX_PATH: "nixpkgs=channel:nixos-20.09"
  nixfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Nix
        uses: cachix/install-nix-action@v12
      - name: Nixfmt
        run: 'nix-shell ./shell.nix --run "find . -iname \"*.nix\" | xargs -I{} nixfmt -c {}"'
        env:
          NIX_PATH: "nixpkgs=channel:nixos-20.09"
